# Generated by Django 4.0.2 on 2022-02-16 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of company', max_length=100)),
                ('company_uuid', models.UUIDField(default=uuid.UUID('fa6b990e-9218-41db-82bc-ce683a8ea863'), help_text='UUID of company', unique=True)),
            ],
        ),
    ]
