# Generated by Django 4.0.2 on 2022-02-16 02:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_uuid',
            field=models.UUIDField(default=uuid.UUID('4a62bd5f-96cc-4eaa-92c2-6576be36db9a'), help_text='UUID of company', unique=True),
        ),
    ]
